# Request
# float64 rate
float64 duration
string color

# nowadays these request fields seem unused

# bool striplights
# bool headlights
# bool glowlights
---
# Response
bool finished
string debug_msg
---
# Feedback
float64 time_remaining
